inputs:
  password:
    type: password
    label: "Access Password"
    description: "Password to log in to Code Server"
    generate: true
    required: true

services:
  main:
    image: docker.io/codercom/code-server:latest
    bind_ports: [8080]
    environment:
      PASSWORD: "{{ .Inputs.password }}"
      SUDO_PASSWORD: "{{ .Inputs.password }}"
    storage:
      persistent:
        config:
          container: /home/coder/.config
          size_limit: 1GB
        project:
          container: /home/coder/project
          size_limit: 10GB

listeners:
  - name: __primary
    guest_port: 8080
    flow: tcp
    protocol: http

x-piccolo:
  mode: workspace
