name: code-server
image: docker.io/codercom/code-server:latest

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access Code Server"
    default: "code"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

  password:
    type: password
    label: "Access Password"
    description: "Password to log in to Code Server"
    generate: true
    required: true

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 8080
    flow: tcp
    protocol: http

environment:
  PASSWORD: "{{ .Inputs.password }}"
  SUDO_PASSWORD: "{{ .Inputs.password }}"

storage:
  persistent:
    config:
      container: /home/coder/.config
      size_limit: 1GB
    project:
      container: /home/coder/project
      size_limit: 10GB