name: immich

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access Immich (e.g., 'photos' -> photos.domain.tld)"
    default: "photos"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

  postgres_password:
    type: password
    label: "Database Password"
    generate: true
    required: true

type: user

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 2283
    flow: tcp
    protocol: http
    remote_ports: [80, 443]
    auth:
      rules:
        - path: "/.well-known/"
          type: prefix
          strategy: public
        - path: "/api/server-info/ping"
          type: exact
          strategy: public
        - path: "/"
          type: prefix
          strategy: oidc_passthrough

permissions:
  network:
    internet: allow
    local_network: allow
    dns: allow
  filesystem:
    read_only_root: false
  resources:
    max_processes: 500
    max_open_files: 4096

healthcheck:
  http:
    path: /api/server-info/ping
    port: "{{ .Inputs.subdomain }}"
    timeout: 10s
    retries: 5

x-piccolo:
  mode: service
  replication:
    hot:
      datasets: [disk, data]
    cold:
      datasets: [disk, data]
      rpo: 1h
      consistency: crash_consistent
  secrets:
    injection: mixed

primary_service: server

services:
  server:
    image: ghcr.io/immich-app/immich-server:v2
    bind_ports: [2283]
    after: [database, redis]
    oidc_client:
      redirect_uri_paths:
        - "/auth/login"
        - "/user-settings"
      redirect_uris:
        - "app.immich:///oauth-callback"
      ca_mount_path: "/etc/ssl/certs/piccolo-ca.crt"
      env:
        IMMICH_OAUTH_ISSUER_URL: "{{ .System.Auth.Issuer }}"
        IMMICH_OAUTH_CLIENT_ID: "{{ .System.Auth.ClientID }}"
        IMMICH_OAUTH_CLIENT_SECRET: "{{ .System.Auth.ClientSecret }}"
    environment:
      # Database connection
      DB_HOSTNAME: "127.0.0.1"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "{{ .Inputs.postgres_password }}"
      DB_DATABASE_NAME: "immich"
      # IMMICH_CONFIG_FILE: "/usr/src/app/config.json"
      
      # Redis connection
      REDIS_HOSTNAME: "127.0.0.1"
      
      # ML Service connection
      IMMICH_MACHINE_LEARNING_URL: "http://127.0.0.1:3003"
      
      # Storage locations
      UPLOAD_LOCATION: "/data"
      
      # General
      IMMICH_PORT: "2283"
      LOG_LEVEL: "log"
      
      # Auth
      NODE_EXTRA_CA_CERTS: "/etc/ssl/certs/piccolo-ca.crt"
    
    storage:
      persistent:
        upload-data:
          container: /data
    
    resources:
      limits:
        memory: 4GB
        cpu: 2.0

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2
    bind_ports: [3003]
    storage:
      persistent:
        model-cache:
          container: /cache
    resources:
      limits:
        memory: 2GB
        cpu: 2.0

  redis:
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    bind_ports: [6379]
    resources:
      limits:
        memory: 512MB
        cpu: 1.0

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    bind_ports: [5432]
    environment:
      POSTGRES_PASSWORD: "{{ .Inputs.postgres_password }}"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "immich"
      POSTGRES_INITDB_ARGS: "--data-checksums"
    storage:
      persistent:
        pgdata:
          container: /var/lib/postgresql/data
    resources:
      limits:
        memory: 2GB
        cpu: 2.0