name: uptimekuma

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access Uptime Kuma (e.g., 'uptime' -> uptime.your-domain.com)"
    default: "uptime"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

services:
  main:
    image: docker.io/louislam/uptime-kuma:1
    bind_ports: [3001]
    storage:
      persistent:
        data:
          container: /app/data
          size_limit: 2GB

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 3001
    flow: tcp
    protocol: http
    auth:
      rules:
        - path: "/"
          type: prefix
          strategy: public

x-piccolo:
  mode: service