name: uptime-kuma
image: docker.io/louislam/uptime-kuma:1

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access Uptime Kuma (e.g., 'uptime' -> uptime.your-domain.com)"
    default: "uptime"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 3001
    flow: tcp
    protocol: http
storage:
  persistent:
    data:
      container: /app/data
      size_limit: 2GB

x-piccolo:
  mode: service