services:
  main:
    image: docker.io/louislam/uptime-kuma:1
    bind_ports: [3001]
    storage:
      persistent:
        data:
          container: /app/data
          size_limit: 2GB

listeners:
  - name: __primary
    guest_port: 3001
    flow: tcp
    protocol: http
    auth:
      rules:
        - path: "/"
          type: prefix
          strategy: public

x-piccolo:
  mode: service
