name: wsnginx
type: user

inputs:
  subdomain:
    type: string
    label: Subdomain
    description: The subdomain for accessing this web server
    default: nginx
    required: true
    validation:
      regex: "^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$"
      message: Must be lowercase alphanumeric with optional hyphens

services:
  main:
    image: nginx:alpine
    bind_ports: [80]

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 80
    flow: tcp
    protocol: http
    remote_ports: [80, 443]

x-piccolo:
  mode: workspace
