type: user

services:
  main:
    image: nginx:alpine
    bind_ports: [80]

listeners:
  - name: __primary
    guest_port: 80
    flow: tcp
    protocol: http
    remote_ports: [80, 443]

x-piccolo:
  mode: workspace