services:
  main:
    image: ghcr.io/sysadminsmedia/homebox:latest
    bind_ports: [7745]
    storage:
      persistent:
        data:
          container: /data
          size_limit: 5GB

listeners:
  - name: __primary
    guest_port: 7745
    flow: tcp
    protocol: http

x-piccolo:
  mode: service
