name: homebox
image: ghcr.io/sysadminsmedia/homebox:latest

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access Homebox"
    default: "homebox"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 7745
    flow: tcp
    protocol: http
storage:
  persistent:
    data:
      container: /data
      size_limit: 5GB

x-piccolo:
  mode: service