name: redis
image: docker.io/library/redis:7

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access Redis"
    default: "redis"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 6379
    flow: tcp
    protocol: raw
storage:
  persistent:
    data:
      container: /data
      size_limit: 1GB

x-piccolo:
  mode: service