name: redis

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access Redis"
    default: "redis"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

services:
  main:
    image: docker.io/library/redis:7
    bind_ports: [6379]
    storage:
      persistent:
        data:
          container: /data
          size_limit: 1GB

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 6379
    flow: tcp
    protocol: raw

x-piccolo:
  mode: service