name: wordpress

inputs:
  subdomain:
    type: string
    label: "Subdomain"
    description: "The address to access the blog"
    default: "blog"
    required: true
    validation:
      regex: "^[a-z0-9-]+$"
      message: "Only lowercase letters, numbers, and hyphens allowed."

services:
  main:
    image: docker.io/library/wordpress:6
    bind_ports: [80]
    storage:
      persistent:
        wp-content:
          container: /var/www/html
          size_limit: 5GB

listeners:
  - name: "{{ .Inputs.subdomain }}"
    guest_port: 80
    flow: tcp
    protocol: http
    auth:
      rules:
        - path: "/wp-admin/"
          type: prefix
          strategy: protected
        - path: "/wp-login.php"
          type: exact
          strategy: protected
        - path: "/"
          type: prefix
          strategy: public

x-piccolo:
  mode: service